### ISSUE TITLE
can support real time asr?

### ISSUE THREAD

**Issue by herbiel** [YuanGongND/whisper-at#14]
can support real time asr?

**Comment by YuanGongND** [comment]
The minimal window of whisper-at is 0.4s, you can check the model's performance when the window is 0.4s. 

The code is based on the original OpenAI whisper, if you want to implement in on a real-time version of Whisper, you would need some additional engineering.

-Yuan

**Comment by herbiel** [comment]
a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/19.npz
a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/05.npz
a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/03.npz
a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/03.npz
a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/08.npz
a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/09.npz
a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/16.npz
Traceback (most recent call last):
  File "/opt/whisper/whisper-at/src/whisper_at_train/./run.py", line 152, in <module>
    train(audio_model, train_loader, val_loader, args)
  File "/opt/whisper/whisper-at/src/whisper_at_train/traintest.py", line 96, in train
    audio_output = audio_model(a_input)
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/whisper/whisper-at/src/whisper_at_train/models.py", line 172, in forward
    audio_rep = audio_rep.reshape(B*self.n_layer, audio_rep.shape[2], audio_rep.shape[3]) # [B*32, 25, 1280]
RuntimeError: shape '[192, 25, 512]' is invalid for input of size 3686400 


i try use the 8K audio to train ,but with some problem,can you help me /

**Comment by YuanGongND** [comment]
> audio_rep = audio_rep.reshape(Bself.n_layer, audio_rep.shape[2], audio_rep.shape[3]) # [B32, 25, 1280]
> RuntimeError: shape '[192, 25, 512]' is invalid for input of size 3686400
> 
> i try use the 8K audio to train ,but with some problem,can you help me 

These are two things, first, whisper resamples audio to 16kHz so it does not matter your input sampling rate. See https://github.com/openai/whisper/discussions/870 

> a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/19.npz
> a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/05.npz
> a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/03.npz
> a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/03.npz
> a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/08.npz
> a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/09.npz
> a missing file /data/sls/scratch/yuangong/whisper-a/feat_as_full/whisper_tiny/16.npz

You are missing the input features, you need to extract and save feature and then train the model please follow the Readme, especially section 2.1 https://github.com/YuanGongND/whisper-at#part-2-whisper-at-training.

Since your audio will internally convert to 16kHz anyways, you can also explicitly do it using `sox` and test in with our hugging face space demo at https://huggingface.co/spaces/yuangongfdu/whisper-at. 

-Yuan

**Comment by herbiel** [comment]
(whisper) root@ubuntu-server:/opt/whisper/whisper-at/src/noise_robust_asr/intermediate_feat_extract/as_full# sh extract_as_full_whisper_all.sh 0
+ export TORCH_HOME=../../pretrained_models
+ python extract_as_full_whisper_all.py --split 0
/root/miniconda3/envs/whisper/lib/python3.10/site-packages/whisper/timing.py:58: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
cuda
Traceback (most recent call last):
  File "/opt/whisper/whisper-at/src/noise_robust_asr/intermediate_feat_extract/as_full/extract_as_full_whisper_all.py", line 55, in <module>
    model = Whisper(dims)
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/whisper/model.py", line 225, in __init__
    self.encoder = AudioEncoder(
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/whisper/model.py", line 148, in __init__
    self.conv1 = Conv1d(n_mels, n_state, kernel_size=3, padding=1)
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 300, in __init__
    super(Conv1d, self).__init__(
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 137, in __init__
    self.weight = Parameter(torch.empty(
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1287, in __setattr__
    self.register_parameter(name, value)
  File "/root/miniconda3/envs/whisper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 416, in register_parameter
    raise KeyError("attribute '{}' already exists".format(name))
KeyError: "attribute 'weight' already exists" still can't run
