### ISSUE TITLE
whisper-at does not recognize laughter

### ISSUE THREAD

**Issue by Shivansh-yadav13** [YuanGongND/whisper-at#7]
I was testing whisper-at on hugging face and I found out that it does not recognize laughter.
I'm specifically looking for a solution to recognize laughter.

**Comment by YuanGongND** [comment]
Hi there,

Please check our [Colab Tutorial](https://colab.research.google.com/drive/1BbOGWCMjkOlOY5PbEMGk5RomRSqMcy_Q?usp=sharing). We provide functions to change the threshold and class of interest. 

Specifically for your case, after install Whisper-AT, 

```python3
import whisper_at as whisper

audio_tagging_time_resolution = 10
model = whisper.load_model("large-v1")
result = model.transcribe("audio.mp3", at_time_res=audio_tagging_time_resolution)

# ASR Results
print(result["text"])

# Audio Tagging Results
audio_tag_result = whisper.parse_at_label(result, language='follow_asr', top_k=1, p_threshold=-5, include_class_list=[16]))
```

Where `[16]` is the index of the laughter class, and please tune `p_threshold`.

-Yuan

**Comment by Shivansh-yadav13** [comment]
@YuanGongND 
I got this error installing `whisper-at`
on a new conda env with python 3.9

```bash
Collecting whisper-at
  Obtaining dependency information for whisper-at from https://files.pythonhosted.org/packages/72/d2/7042fbcaa69101b6dfc8623e9acb8420143417a0e6f1f55a7b5cee1d2f0f/whisper_at-0.4-py3-none-any.whl.metadata
  Using cached whisper_at-0.4-py3-none-any.whl.metadata (20 kB)
INFO: pip is looking at multiple versions of whisper-at to determine which version is compatible with other requirements. This could take a while.
  Obtaining dependency information for whisper-at from https://files.pythonhosted.org/packages/b2/d1/5fae993426fbbc92dffb1057f415ab464057e489df03203b408f31568a60/whisper_at-0.2-py3-none-any.whl.metadata
  Using cached whisper_at-0.2-py3-none-any.whl.metadata (18 kB)
  Obtaining dependency information for whisper-at from https://files.pythonhosted.org/packages/56/f4/891cae6f547cf395568226d15161e1df1abb62f5e4de62cb5eb4dd374080/whisper_at-0.1-py3-none-any.whl.metadata
  Using cached whisper_at-0.1-py3-none-any.whl.metadata (16 kB)
ERROR: Cannot install whisper-at==0.1, whisper-at==0.2 and whisper-at==0.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    whisper-at 0.4 depends on triton==2.0.0
    whisper-at 0.2 depends on triton==2.0.0
    whisper-at 0.1 depends on triton==2.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

**Comment by YuanGongND** [comment]
Please use this (see our readme).

```
# install all dependencies except triton
pip install numba numpy torch tqdm more-itertools tiktoken==0.3.3
# install whisper-at without any dependency
pip install --no-deps whisper-at  
```

-Yuan

**Comment by Shivansh-yadav13** [comment]
@YuanGongND 

using the `large-v1` model
it's giving this error
```bash
Traceback (most recent call last):
  File "N:\whisperat\main.py", line 4, in <module>
    model = whisper.load_model("large-v1")
  File "C:\Users\Admin\anaconda3\envs\whisperatenv\lib\site-packages\whisper_at\__init__.py", line 175, in load_model
    checkpoint = torch.load(fp, map_location=device)
  File "C:\Users\Admin\anaconda3\envs\whisperatenv\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Admin\anaconda3\envs\whisperatenv\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

similarly when I used the `large` model after downloading its showing the same error
```bash
100%|███████████████████████████████████████| 153M/153M [00:12<00:00, 12.5MiB/s]
Traceback (most recent call last):
  File "N:\whisperat\main.py", line 4, in <module>
    model = whisper.load_model("large")
  File "C:\Users\Admin\anaconda3\envs\whisperatenv\lib\site-packages\whisper_at\__init__.py", line 175, in load_model
    checkpoint = torch.load(fp, map_location=device)
  File "C:\Users\Admin\anaconda3\envs\whisperatenv\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Admin\anaconda3\envs\whisperatenv\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

using the `medium` model does not give any tags.

**Comment by YuanGongND** [comment]
> using the medium model does not give any tags.

```
audio_tag_result = whisper.parse_at_label(result, 
language='follow_asr', 
top_k=1,  # only care of 1 single class
p_threshold=-5, # please tune this param
include_class_list=[16])) # 16 is the index of Laughter.
```
Please check `p_threshold=` to a smaller value, you would need to tune it, i.e., you can start with a minimal value, e.g., -999, and observe the output `p` for your laugh/non-laugh input, and decide an appropriate value.

> using the large-v1 model it's giving this error

This seems to be related to: https://github.com/YuanGongND/whisper-at/issues/3

Please check your download folder and see if there is a `%` or other invalid char for Windows.

Or use `pip install --upgrade whisper-at` to install the latest version.

-Yuan
